name: CI

on:
  push:
    branches: [main]
  pull_request:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Prepare logs directory
        run: mkdir -p logs
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color=always
      - name: Test
        run: coverage run -m pytest --timeout=60
      - name: Coverage report
        run: |
          coverage xml
          coverage report --fail-under=90
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/latest_railway.log
          if-no-files-found: ignore
