name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install Railway CLI
        run: npm install -g railway
      - name: Prepare logs directory
        run: mkdir -p logs
      - name: Capture Railway logs
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway logs --follow > logs/latest_railway.log &
          echo $! > logs/railway_logs.pid
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color=always
      - name: Install CycloneDX Python SBOM Tool
        run: |
          python -m pip install cyclonedx-bom
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Generate SBOM
        run: |
          cyclonedx-py requirements -i requirements.txt -o logs/sbom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: logs/sbom.xml
      - name: Test
        run: pytest --cov=. --cov-report=xml --cov-report=term
      - name: Coverage report
        run: coverage report --fail-under=90
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        if: ${{ env.SNYK_TOKEN != '' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        run: snyk test
      - name: Stop Railway logs
        if: always()
        run: |
          if [ -f logs/railway_logs.pid ]; then
            kill "$(cat logs/railway_logs.pid)" || true
          else
            pkill railway || true
          fi
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
          if-no-files-found: ignore
