name: Publish Data

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Stage whitelisted data files
        run: |
          git add -f data/units.json data/categories.json
          if git diff --cached --quiet; then
            echo "No data changes to commit"
          else
            git commit -m "Update data files via workflow"
            git push
          fi
