name: Publish Extractor Data

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  extract-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: ./setup.sh

      - name: Run extractor to data/temp/
        run: |
          mkdir -p data/temp
          python scripts/fetch_method.py \
            --output data/temp/units.json \
            --categories data/temp/categories.json

      - name: Commit data to data-sync branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git switch data-sync
          git pull origin data-sync

          cp data/temp/units.json data/units.json
          cp data/temp/categories.json data/categories.json

          git add data/units.json data/categories.json
          git commit -m "Update data from main [CI]" || echo "No changes to commit"
          git push origin data-sync
