name: Publish Extractor Data

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  extract-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: ./setup.sh

      - name: Prepare folders
        run: |
          mkdir -p tmp_data logs data

      - name: Run extractor to tmp_data/
        run: |
          python scripts/fetch_method.py \
            --output tmp_data/units.json \
            --categories tmp_data/categories.json \
            --log-file logs/extractor.json

      - name: Validate JSON output
        run: |
          for f in units.json categories.json; do
            path="tmp_data/$f"
            if [ ! -s "$path" ] || [ $(stat -c%s "$path") -le 2 ]; then
              echo "$f missing or empty" >&2
              exit 1
            fi
            python -m json.tool "$path" > /dev/null || {
              echo "$f is invalid JSON" >&2
              exit 1
            }
          done

      - name: Copy JSON files
        run: |
          mkdir -p data
          if [ -f tmp_data/units.json ]; then
            cp tmp_data/units.json data/units.json
            echo "units.json updated"
          else
            echo "units.json missing" >&2
          fi
          if [ -f tmp_data/categories.json ]; then
            cp tmp_data/categories.json data/categories.json
            echo "categories.json updated"
          else
            echo "categories.json not generated"
          fi

      - name: Commit data to data-sync branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch origin data-sync
          git switch data-sync
          git pull origin data-sync || true

          if [ ! -s data/units.json ] || [ $(stat -c%s data/units.json) -le 2 ]; then
            echo "units.json missing or empty" >&2
            exit 1
          fi
          if [ ! -s data/categories.json ] || [ $(stat -c%s data/categories.json) -le 2 ]; then
            echo "categories.json missing or empty" >&2
            exit 1
          fi

          git add -f data/units.json data/categories.json 2>/dev/null || true

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update data from main [CI]"
          git push origin data-sync

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extractor-logs
          path: logs/
          if-no-files-found: ignore
