name: Railway Logs

on:
  workflow_dispatch:

jobs:
  fetch-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g railway
      - name: Stream Logs
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          mkdir -p logs
          railway logs --follow > logs/latest_railway.log
      - uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: logs/latest_railway.log
