name: Update data

on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Fetch latest data
        run: |
          python scripts/fetch_method.py --timeout 10
      - name: Commit changes
        run: |
          if [[ $(git status --porcelain data/export/units.json data/export/categories.json) ]]; then
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add data/export/units.json data/export/categories.json
            git commit -m 'Update data via workflow'
            git push
          fi
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: extractor-logs
          path: logs/runtime-*.json
